### PR TITLE
Updated to FFI 1.0.0, Null safety

### PR DESCRIPTION
**Pull request by mortenboye**
I had to update to FFI 1.0.0 and null safety for my project, and figured you maybe wanted to merge those changes back in.

### CODE REVIEW

**Comment by ardera** [comment]
looks good, can you format it? Otherwise I can't really see what changed
Just a simple `dart format .` would work I think

**Comment by mortenboye** [comment]
Sure thing

**Comment by ardera** [comment]
I'm not sure I like that you removed `newStruct` and instead call `calloc` directly, and that there are many places where `.ref` is invoked even though it could be avoided. (Also at least the minor version should be increased)

I'll merge it into a dev branch and do some fixups, thanks for the contribution!

**Comment by mortenboye** [comment]
newStruct works with generics, which alloc() doesn’t. That’s why i removed that.

**Comment by ardera** [comment]
that's a good point, but I think you can use `sizeOf<T>()` to get the struct size and make it work with generics

**Pull request merged**
